### ISSUE TITLE
Over 300 failed tests?

### ISSUE THREAD

**Issue by piotr-dobrogost** [kvesteri/sqlalchemy-continuum#104]
I'm posting here as it seems project does not have a mailing list.

I wanted to try out sa-continuum and I started by running tests with `py.test tests`. As a result 319 tests failed, 291 passed, 12 was skipped and 5 ended with an error. This is with SQLAlchemy-Continuum 1.2.0, SQLAlchemy 1.0.8 and SQLAlchemy-Utils 0.30.17.

Are those failed tests result of me not running tests properly?
Output from py.test with the first 10 failures is at https://gist.github.com/piotr-dobrogost/4140267dc9dd654f5560

**Comment by kvesteri** [comment]
I'd guess so (I don't have time now to investigate further). As you can see from [here](https://travis-ci.org/kvesteri/sqlalchemy-continuum) the test suite is being run against various databases (PostgreSQL, MySQL and SQLite) and the tests pass at least on my machine and on the CI servers.
