### ISSUE TITLE
use_property_mod_tracking always set when using sync_trigger even when no not using the plugin

### ISSUE THREAD

**Issue by danielknell** [kvesteri/sqlalchemy-continuum#127]
use_property_mod_tracking is always set when using sync_trigger even when no not using the plugin:

relevant lines in the code are:

https://github.com/kvesteri/sqlalchemy-continuum/blob/c2cd53a5db21d02dda4ee362493af1411111bfd2/sqlalchemy_continuum/dialects/postgresql.py#L492

https://github.com/kvesteri/sqlalchemy-continuum/blob/c2cd53a5db21d02dda4ee362493af1411111bfd2/sqlalchemy_continuum/dialects/postgresql.py#L512

this causes the triggers to fail with "column "foo_mod" does not exist" errors when you dont have the plugin enabled.

**Comment by ztane** [comment]
https://github.com/kvesteri/sqlalchemy-continuum/issues/115

**Comment by ztane** [comment]
Duplicate of https://github.com/kvesteri/sqlalchemy-continuum/issues/115

**Comment by ztane** [comment]
and not only that, but IIRC the code only ever creates triggers for PropertyModTracker.
