### ISSUE TITLE
Memory leaks with UnitOfWork instances

### ISSUE THREAD

**Issue by quantus** [kvesteri/sqlalchemy-continuum#131]
Continuum can leak `UnitOfWork` instances stored in the `VersioningManager`. First of all the items are not removed from the dictionary in function `VersioningManager.clear`. This is simple to fix by adding line `del self.units_of_work[conn]`.

Other issue is that when using continuum with flask-sqlalchemy the function `VersioningManager.clear` gets called with `SignallingSession` after the transaction commit phase is completed. `VersioningManager` uses connections as keys to find the active `UnitOfWork` instance from `unit_of_works` dictionary and when `SignallingSession`'s bind value is an `Engine` instead of `Connection` the manager fails to find the right unit of work instance. Thus the unit of work instance never gets removed from the dictionary even when the del statement is added as above.

The second issue doesn't happen when the `Session` is created with a `Connection` as a bind value, but this isn't possible when using flask-sqlalchemy.

**Comment by fake-name** [comment]
For the love of god, PLEASE release a new version on PyPi. I've been fighting this issue for months, assuming it was fixed.

**Comment by kvesteri** [comment]
Done and sorry for keeping you waiting.

**Comment by fake-name** [comment]
Awesome. I can remove the git dependency in my build process.
