### ISSUE TITLE
FlaskPlugin: use `get_id()`  method instead of `id` attribute

### ISSUE THREAD

**Issue by jirikuncar** [kvesteri/sqlalchemy-continuum#149]
Following Flask-Login documentation we should use `current_user.get_id()` instead of `current_user.id`. See https://flask-login.readthedocs.io/en/latest/#your-user-class

**Comment by anthraxx** [comment]
@marksteward @jirikuncar This is actually a misinterpretation of the API, this commit should be reverted:

The API expects `get_id()` to be a unique *string*, that may or may not be an integer. This feature is only used to uniquely identify the user, but its not the same as the user's primary key.

Please take a note on how `get_id()` is expected to behave on this feature of flask-login:
https://flask-login.readthedocs.io/en/latest/#alternative-tokens
It means it can return any arbitrary string to identify the user which can be swapped to any other value to invalidate all sessions. This explicitly states that it is not the same as the user's primary id which is also used as foreign key on the table.

sqlalchemy-continuum's transaction tables reference the user with a foreign key of the actual id. If a downstream application uses the `alternative-tokens` feature as described by the flask-login documentation, this breaks horribly as sqlalchemy-continuum will then try to insert an arbitrary unique string of the user as the foreign key to reference the user in the user table.

**Comment by marksteward** [comment]
Thanks, yes that does look wrong. I misunderstood the context it was being called in - we shouldn't need to call `get_id` because we're the implementer.
