### ISSUE TITLE
Unable to exclude many-to-many relationships

### ISSUE THREAD

**Issue by mrcarriere** [kvesteri/sqlalchemy-continuum#152]
This seems to be a bit different from the other many-to-many issues here: I have a many-to-many relationship on a versioned table that I don't want tracked by continuum.

Here's a paired down version of the models:

```
from sqlalchemy import Table, Column, DateTime, String, Integer, ForeignKey, Text, func
from sqlalchemy.orm import relationship, backref

from meta import Base 

channel_tag = Table('service_channel_service_tag', Base.metadata,
    Column('channel_id', Integer, ForeignKey('service_channel.id'), primary_key=True),
    Column('tag_id', Integer, ForeignKey('service_tag.id'))
)

class ServiceChannel(Base):
    __tablename__ = 'service_channel'
    __versioned__ = {
        'exclude': ['tags']
    }

    id = Column(Integer, primary_key=True)
    title = Column(Text(convert_unicode=True))
    description = Column(Text(convert_unicode=True))

    tags = relationship("ServiceTag",
                        secondary=channel_tag,
                        backref="channels")

    def __repr__(self):
        return "<ServiceChannel(id='%s')>" % (self.id)

class ServiceTag(Base):
    __tablename__ = 'service_tag'

    id = Column(Integer, primary_key=True)
    tag = Column(String(30), unique=True, nullable=False)

    def __repr__(self):
        return "<ServiceTag(id='%s', tag='%s')>" % (self.id, self.tag)
```

In this particular case, having the historical data of tags is unnecessary. Is there some obvious way to have continuum ignore this that I'm missing?

**Comment by GeorgesTatchum** [comment]
> Please, I currently have the same problem of excluding the many-to-many table because I don't want it to be versioned, but for the moment it is. Here is my code: `make_versioned( user_cls=None, options={ "exclude": ["linked_documents"], }, ) LinkedDocuments = Table( "linked_documents", Base.metadata, Column("document", ForeignKey("documents.uuid"), primary_key=True), Column("linked", ForeignKey("documents.uuid"), primary_key=True), extend_existing=True, )
> 
> @DataClass class Document(Base): """ Document model for storing Document details """
> 
> ```
> __tablename__ = "documents"
> __versioned__ = {"exclude": exclude_tables}
> 
> uuid: str = Column(
>     String(255), primary_key=True, unique=True, index=True, nullable=False
> )
> id_number: str = Column(
>     String(255), unique=False, index=True, nullable=True, default=""
> )
> 
> created_date: any = Column(DateTime(timezone=True), nullable=False)
> place: any = Column(String, unique=False, index=True, nullable=True, default="")
> object: any = Column(Text, unique=False, nullable=True, default="")
> payment_ref: any = Column(String(255), unique=False, nullable=True, default="")
> note: any = Column(Text, unique=False, nullable=True, default="")
> 
> doc_type: any = Column(
>     types.Enum(DocumentType), nullable=True, default=DocumentType.QUOTE
> )
> invoice_type: any = Column(types.Enum(InvoiceType), nullable=True, default=None)
> state: any = Column(
>     types.Enum(DocumentState), nullable=True, default=DocumentState.DRAFT
> )
> payment_mode: any = Column(
>     types.Enum(PaymentMode), nullable=True, default=PaymentMode.CASH
> )
> expense_type: any = Column(types.Enum(ExpenseType), nullable=True, default=None)
> 
> is_signed: bool = Column(Boolean, unique=False, nullable=True, default=False)
> signed_with_global_tva: bool = Column(
>     Boolean, unique=False, nullable=True, default=False
> )
> signed_with_global_discount: bool = Column(
>     Boolean, unique=False, nullable=True, default=False
> )
> signed_with_references: bool = Column(
>     Boolean, unique=False, nullable=True, default=False
> )
> signed_with_subtotal: bool = Column(
>     Boolean, unique=False, nullable=True, default=False
> )
> is_deleted: bool = Column(Boolean, unique=False, nullable=True, default=False)
> 
> paid_percent: float = Column(Float, unique=False, nullable=True, default=0.0)
> paid_amount: float = Column(Float, unique=False, nullable=True, default=0.0)
> total_ttc_amount: float = Column(Float, unique=False, nullable=True, default=0.0)
> total_amount: float = Column(Float, unique=False, nullable=True, default=0.0)
> total_discount: float = Column(Float, unique=False, nullable=True, default=0.0)
> 
> deadline: any = Column(Date(), nullable=True)
> date_added: any = Column(DateTime(timezone=True), server_default=func.now())
> date_modified: any = Column(
>     DateTime(timezone=True), server_default=func.now(), onupdate=datetime.now()
> )
> 
> user_uid = Column(
>     String(255), ForeignKey("users.uuid", ondelete="CASCADE"), nullable=True
> )
> user = relationship("User", foreign_keys=[user_uid])
> 
> author_uid = Column(
>     String(255), ForeignKey("users.uuid", ondelete="CASCADE"), nullable=True
> )
> author = relationship("User", foreign_keys=[author_uid])
> 
> quote_uuid: str = Column(
>     String, ForeignKey("documents.uuid", ondelete="CASCADE"), nullable=True
> )
> quote = relationship("Document", remote_side=[uuid])
> 
> signing_file_uuid: str = Column(
>     String, ForeignKey("storages.uuid", ondelete="CASCADE"), nullable=True
> )
> signing_file = relationship("Storage", foreign_keys=[signing_file_uuid])
> 
> printed_counter: int = Column(Integer, unique=False, nullable=True, default=0)
> 
> linked_documents = relationship(
>     "Document",
>     secondary=LinkedDocuments,
>     primaryjoin=uuid == LinkedDocuments.c.document,
>     secondaryjoin=uuid == LinkedDocuments.c.linked,
>     backref="documents",
> )
> 
> def clone(
>     self,
>     id_number: str,
>     doc_type: DocumentType,
>     state: DocumentState,
>     author_id: str,
>     created_date: datetime,
>     quote_uid: str,
>     invoice_type: Optional[InvoiceType] = None,
> ) -> "Document":
>     """
>     Clone the current instance of Document with some different values
>     """
>     clone_instance = Document()
>     clone_instance.uuid = str(uuid.uuid4())  # Générer un nouveau UUID
>     clone_instance.id_number = id_number
>     clone_instance.created_date = created_date
>     clone_instance.place = self.place
>     clone_instance.object = self.object
>     clone_instance.payment_ref = self.payment_ref
>     clone_instance.note = self.note
>     clone_instance.doc_type = doc_type
>     clone_instance.invoice_type = (
>         invoice_type if invoice_type else self.invoice_type
>     )
>     clone_instance.state = state
>     clone_instance.payment_mode = self.payment_mode
>     # clone_instance.is_signed = self.is_signed
>     clone_instance.signed_with_global_tva = self.signed_with_global_tva
>     clone_instance.signed_with_global_discount = self.signed_with_global_discount
>     clone_instance.signed_with_references = self.signed_with_references
>     clone_instance.signed_with_subtotal = self.signed_with_subtotal
>     clone_instance.paid_percent = self.paid_percent
>     clone_instance.paid_amount = self.paid_amount
>     clone_instance.total_ttc_amount = self.total_ttc_amount
>     clone_instance.total_amount = self.total_amount
>     clone_instance.total_discount = self.total_discount
>     clone_instance.user_uid = self.user_uid
>     clone_instance.author_uid = author_id
>     clone_instance.quote_uuid = quote_uid if quote_uid else self.uuid
>     # clone_instance.signing_file_uuid = self.signing_file_uuid
> 
>     return clone_instance
> ```
> 
> `

I'm using :  SQLAlchemy-Continuum==1.4.0
