### ISSUE TITLE
PostgreSQL table name not in double-quotes

### ISSUE THREAD

**Issue by merqurio** [kvesteri/sqlalchemy-continuum#164]
I have mixed-case spelling table, and `continuum` ist trying to query it with all lower-case. This might be due to the lack of double-quotes to delimit identifiers.

I guess that adding double quotes for example [here](https://github.com/kvesteri/sqlalchemy-continuum/blob/5f682e6e5bf038d8069db51e58f71d2c1dbed6c6/sqlalchemy_continuum/dialects/postgresql.py#L15) should be sufficient.

Is this something intended ? Would you accept a PR on this ?

```
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) relation "narrative_version" does not exist
LINE 1: UPDATE Narrative_version
               ^
QUERY:  UPDATE Narrative_version
SET end_transaction_id = transaction_id_value
WHERE
    transaction_id = (
        SELECT MIN(transaction_id) FROM Narrative_version
        WHERE end_transaction_id IS NULL AND "id" = NEW."id"
    ) AND
    "id" = NEW."id"
CONTEXT:  PL/pgSQL function narrative_audit() line 15 at SQL statement
```

**Comment by kvesteri** [comment]
Yeah definitely, PR's for this are welcome :+1:

**Comment by merqurio** [comment]
I was totally unable to get this working. If I double quote all the queries, sometimes I get a pair   of doblequotes (`"tableName"`) and another time 2 pairs (`""tableName""`). Any suggestion to make this work and send the PR ? Thanks !
