### ISSUE TITLE
Deadlock in MySQL update queries

### ISSUE THREAD

**Issue by adityav-verma** [kvesteri/sqlalchemy-continuum#172]
## What?
```
sqlalchemy.exc:OperationalError: (_mysql_exceptions.OperationalError)
(1213, 'Deadlock found when trying to get lock; try restarting transaction')
```
Happens quite frequently when sqlalchemy-continuum tries to update the `end_transaction_id`.

**Comment by dlmiddlecote** [comment]
Any update on this issue?

**Comment by marksteward** [comment]
Got a repro?

**Comment by furoxr** [comment]
That frequently happens with strategy config set 'validity'. Change the config to 'subquery' could fix it. 
Like this:
``` python
from sqlalchemy_continuum import make_versioned
make_versioned(options={'strategy': 'subquery'})
```

if you want to know the reason why the dead lock happens, refer to this  1. [gap lock issue of innodb](https://bugs.mysql.com/bug.php?id=1866) 2. [One more InnoDB gap lock to avoid](https://www.percona.com/blog/2013/12/12/one-more-innodb-gap-lock-to-avoid/)

**Comment by mfulgo** [comment]
@marksteward - Unfortunately, I don't have a this running in a single unit test, but below are the steps I'm able to use to reproduce the problem. Perhaps others can convert this into something that can reproduce the issue from within a single test run...

Create a new test (`tests/test_issue_172.py`):
```python
import sqlalchemy as sa
from os import environ, getpid
from sqlalchemy import func
from tests import TestCase


class TestIssue172(TestCase):
    def create_models(self):
        class Article(self.Model):
            __tablename__ = 'article'
            __versioned__ = {
                'base_classes': (self.Model, ),
                'strategy': 'validity'
            }
            id = sa.Column(sa.Integer, autoincrement=True, primary_key=True)

            name = sa.Column(sa.Unicode(255))

        self.Article = Article

    def create_tables(self):
        if environ.get("CREATE_TABLES") == "true":
            TestCase.create_tables(self)

    def drop_tables(self):
        pass

    def test_create_many_records(self):
        pid = getpid()
        for i in range(1, 1001):
            article = self.Article(name=f'Article {pid}-{i:04}')
            self.session.add(article)
            self.session.commit()
        assert self.session.query(func.count(self.Article.id)).\
            where(self.Article.name.like(f'Article {pid}-%')).\
            scalar() == 1000

```

Run the following:
```bash
docker run --rm -e MYSQL_DATABASE='sqlalchemy_continuum_test' -e MYSQL_ALLOW_EMPTY_PASSWORD='yes' -p 127.0.0.1:3306:3306 -d --name mysql mysql:8.0 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
sleep 20

export DB=mysql
CREATE_TABLES=true pytest tests/test_issue_172.py
for i in 1 2 3 4; do pytest tests/test_issue_172.py > test${i}.log & done
jobs # most of the jobs should fail
```
This failed on `v1.3.13`. Here's [a gist with the failed log output](https://gist.github.com/mfulgo/723b17f1344231f0e96ec4bfbbb58afa).

----------
On a completely separate note, it would be helpful to folks who are new to the project to have some kind of quick start guide on how to build and test the project locally. I had to make some guesses based off of the tests' init and what I found in the GHA workflow. I can make a PR for doc updates, if you'd like, but y'all probably have a different approach for setting up your dev environments. 🤷
