### ISSUE TITLE
When using SQLAlchemy 1.3.x, configure_mappers() throws an attribute error

### ISSUE THREAD

**Issue by scottrmercer** [kvesteri/sqlalchemy-continuum#218]
When running `SQLAlchemy >= 1.3.0` making a call to `configure_mappers()` throws the following: 
`models.py:1116: in <module>
    orm.configure_mappers()
../../../../.local/share/virtualenvs/serverless_api-rsKB6esd/lib/python3.6/site-packages/sqlalchemy/orm/mapper.py:3246: in configure_mappers
    Mapper.dispatch._for_class(Mapper).after_configured()
../../../../.local/share/virtualenvs/serverless_api-rsKB6esd/lib/python3.6/site-packages/sqlalchemy/event/attr.py:259: in __call__
    fn(*args, **kw)
../../../../.local/share/virtualenvs/serverless_api-rsKB6esd/lib/python3.6/site-packages/sqlalchemy/orm/events.py:639: in wrap
    fn(*arg, **kw)
../../../../.local/share/virtualenvs/serverless_api-rsKB6esd/lib/python3.6/site-packages/sqlalchemy_continuum/builder.py:173: in configure_versioned_classes
    self.build_relationships(pending_copy)
../../../../.local/share/virtualenvs/serverless_api-rsKB6esd/lib/python3.6/site-packages/sqlalchemy_continuum/builder.py:113: in build_relationships
    builder()
../../../../.local/share/virtualenvs/serverless_api-rsKB6esd/lib/python3.6/site-packages/sqlalchemy_continuum/relationship_builder.py:358: in __call__
    if column_pair[0] in self.property.table.c.values():
../../../../.local/share/virtualenvs/serverless_api-rsKB6esd/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py:949: in __getattr__
    return self._fallback_getattr(key)
../../../../.local/share/virtualenvs/serverless_api-rsKB6esd/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py:923: in _fallback_getattr
    raise AttributeError(key)
E   AttributeError: table`

If I downgrade SQLAlchemy to any version below 1.3.0, it functions as expected. 

When running version 1.3, if I remove the call to `make_versioned()`, tests will pass again (however, versioning does not work, as expected)

**Comment by vault** [comment]
I'm seeing the same issue.

**Comment by kvesteri** [comment]
Fixed as part of 1.3.9
