### ISSUE TITLE
Open License?

### ISSUE THREAD

**Issue by MattOates** [kvesteri/sqlalchemy-continuum#224]
The current LICENSE file is quite minimal in explicitly laying out what is and is not permitted, especially for third party forks for commercial use. Given there is no active support, and many open PRs, if others are to use Continuum or to continue developing it, a more solid open source license would be useful to see. Is the code intended to be free contribution but not free use? Which is what the current license implies.

Could you please clear up what your intent is for the future of sqlalchemy-continuum? and if you're happy for others to take it forwards, either contributing to this repository or are forks acceptable to you.

**Comment by MattOates** [comment]
Maybe helpful https://choosealicense.com/licenses/ https://opensource.org/licenses/category

**Comment by kvesteri** [comment]
The license is intended to be BSD license. Use the package in any way you like, fork it, take over it - your choice :)

Continuum has become quite stale since our company no longer uses it. We use a faster and more versatile alternative: https://github.com/kvesteri/postgresql-audit

That package could be expanded to support other databases. However I don't have any interest in doing that since our company heavily relies on PostgreSQL

**Comment by MattOates** [comment]
Thanks for the clarification, and your work on all this @kvesteri . postgresql-audit looks great but we already have a similar log of changes type solution via Debezium. We have a use case of slower lower volume writes, but desire a more logical representation of a records state at a given time natively.

**Comment by marksteward** [comment]
Looks like you need to tweak the wording for GitHub to recognise it:

```
-* The names of the contributors may not be used to endorse or promote products
-  derived from this software without specific prior written permission.
+* Neither the name of the copyright holder nor the names of its
+  contributors may be used to endorse or promote products derived from
+  this software without specific prior written permission.
```

See https://github.com/marksteward/sqlalchemy-continuum (https://github.com/marksteward/sqlalchemy-continuum/commit/1f644cd)

**Comment by kvesteri** [comment]
You can make this change, you have my approval 😎
