### ISSUE TITLE
track_association_operations out of range

### ISSUE THREAD

**Issue by jellevanwezel** [kvesteri/sqlalchemy-continuum#266]
Hi, 

When I try to version a simple table, I get an index out of range error in `manager.py` on line 454.
In the function `track_association_operations`

```python
table_name = statement.split(' ')[2]
```

Here it assumes the `statement` is either an:

```sql
REMOVE FROM <TABLE_NAME>
``` 
or an 
```sql
INSERT INTO <TABLE_NAME>
```

However, this is not always the case.
In my case, it also triggers when the `statement` is:

```sql
SELECT nextval(...)
```
Then the table name extraction fails.

From the `context`  I see the actual compiled statement is an insert on some sequence table.
This table is created by this plugin.

Am I doing something wrong on the implementations side?

**Comment by marksteward** [comment]
Are you using MariaDB? If so, this is a change in SQLAlchemy 1.4 - see #264

**Comment by jellevanwezel** [comment]
Yes, that is it!
So it's already on the radar
Then this issue can be closed

Thanks!
