### ISSUE TITLE
Searching for deleted elements

### ISSUE THREAD

**Issue by kageurufu** [kvesteri/sqlalchemy-continuum#29]
I'm unable to find how to find deleted objects through the versioning when using the flask TransactionLogBase
My problem is due to the fact that when a versioned table entry is deleted, the deleted transaction log is completely empty, with only the operation_type Operations.DELETE
If this could be done easily with the tx_meta, that would work for me.

I'm hoping to implement a full undo style feature to allow my users to revert changes or even deletions of their entities

**Comment by sanju4115** [comment]
how to use 'store_data_at_delete' ?? please explain
