### ISSUE TITLE
Rewrite TestFlaskPluginWithoutRequestContext

### ISSUE THREAD

**Issue by marksteward** [kvesteri/sqlalchemy-continuum#307]
I tried removing `_app_ctx` and `_request_ctx` and it [broke this test](https://github.com/kvesteri/sqlalchemy-continuum/actions/runs/2984900242) because there's no `login_manager`.

It only worked in previous versions of flask-login because the code would avoid referencing `current_user` when outside a context. However, flask-login doesn't seem to think that's a scenario that can happen.

Presumably the test is for flask shell, but we should confirm that and be clearer about what our contract is.

**Comment by rubencho** [comment]
Hi @marksteward
I think using flask's modules `has_app_context` and `has_request_context` the test can be solved and backwards compatibility with flask/flask-login

**Comment by marksteward** [comment]
I've rebased this to https://github.com/kvesteri/sqlalchemy-continuum/tree/rubencho-fix_307 and will merge if tests pass.

**Comment by marksteward** [comment]
Merged, thanks for this @rubencho!
