### ISSUE TITLE
when autocommit isolation mode used, rollback at transaction level is not resulting in rollback of continuum transactions

### ISSUE THREAD

**Issue by chicco785** [kvesteri/sqlalchemy-continuum#333]
as described in the title, when on an engine connection we configure 
`connection.execution_options(isolation_level="AUTOCOMMIT")` in case of transaction rollback, continuum related transactions are not removed from the database.

**Comment by marksteward** [comment]
Does this only affect SQLAlchemy 1.4 or above in future mode? Can you share some code to reproduce it?

**Comment by chicco785** [comment]
I am currently using SQLAlchemy 2.0 and continuum 1.4 version, i will try to provide you a minimal snipped of code to demo it (i need to extract it from my code)

**Comment by marksteward** [comment]
`connection.begin` should be a no-op under `isolation_level="AUTOCOMMIT"`. You should see warnings in the logs to say so.

**Comment by marksteward** [comment]
I'm guessing you don't actually need autocommit semantics, but if you do, have a look at the [native versioning](https://sqlalchemy-continuum.readthedocs.io/en/latest/native_versioning.html) plugin.

**Comment by chicco785** [comment]
thx
