### ISSUE TITLE
sqlalchemy.exc.SADeprecationWarning on from sqlalchemy_continuum import make_versioned with sqlalchemy > 2

### ISSUE THREAD

**Issue by jhannink** [kvesteri/sqlalchemy-continuum#345]
I am using `sqlalchemy-continuum == 1.4.0` and `sqlalchemy == 2.0.21` and trying to do the following:
```python
from sqlalchemy_continuum import make_versioned
```
which results in 

```python
E   sqlalchemy.exc.SADeprecationWarning: The `sqlalchemy.orm.mapper()` symbol is deprecated and will be removed in a future release. For the mapper-wide event target, use the 'sqlalchemy.orm.Mapper' class.
```

The reason/fix for this probably described here: https://docs.sqlalchemy.org/en/20/changelog/migration_20.html#the-original-mapper-function-now-a-core-element-of-declarative-renamed

 Basically my question is
- Does `sqlalchemy-continuum == 1.4.0` work reliably with `sqlalchemy > 2` yet?

**Comment by marksteward** [comment]
Yes, it's just a deprecation. We'll update before it's removed.

**Comment by jhannink** [comment]
Ah, now I see it too. Was still running with warnings as errors to not miss them during updating to sqlalchemy > 2 😂 
Thx
