### ISSUE TITLE
Patch or Minor Version for a7a6bd7 & ccd8707

### ISSUE THREAD

**Issue by padlocked17** [kvesteri/sqlalchemy-continuum#350]
@marksteward  Any chance we could get a patch or minor version released for a7a6bd7952185b1f82af985c0271834d886a617c? This is preventing the package from running with the new version of Flask and it would make sense to release this in the wild vs forking just to get the updated commit here on the flask plugin.

Thanks!

**Comment by marksteward** [comment]
Sorry, I completely missed this! I've released 1.4.1, which pins to SQLAlchemy 2.0.21 for now (see https://github.com/sqlalchemy/sqlalchemy/discussions/10474)

**Comment by marksteward** [comment]
See https://github.com/kvesteri/sqlalchemy-utils/pull/725. I can unpin it now if that's important.

**Comment by jllopezpino** [comment]
Oh I see! Thank you for pointing it out. No rush at all, it's not a problem for me.
