### ISSUE TITLE
__str__ inheritance

### ISSUE THREAD

**Issue by onlygecko** [kvesteri/sqlalchemy-continuum#92]
Hi,

what am I doing wrong that the `__str__` method of my ModelClass is no inherited to the ModelVersion class? Or is this the issue discussed in #54?

What options do I have?

```python

class Article(Base):

    __tablename__ = 'articles'
    __versioned__ = {}
    id = sa.Column(sa.Integer, sa.Sequence('article_seq'), primary_key=True)
    name = sa.Column(sa.Unicode(255), nullable=False)

    __str__(self):
        return self.name
```

Thanks in advance for your replies. :-)
Peter

**Comment by kvesteri** [comment]
This is essentially the same issue as #54. A viable option is to have both classes inherit some mixin with common functionality.
